[package]
name = "pen-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
num-rational.workspace = true
pen-core = { path = "../pen-core" }
pen-type = { path = "../pen-type" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
