//! Source-bound execution of the registered Step-8 R2 signatures.
//!
//! The term signatures are checked in the ordinary Schema2 fragment and the
//! cube reference is joined to the existing exact-prefix S3 bundle.  This
//! retires the representation failure (F-Q1) for the registered reading.  It
//! does not decide whether coherence or cell action is generated by the
//! operation's naturality basis; that separate R2 question remains F-Q4.

use crate::context::{BinderId, Declaration, TermExpr, TypeExpr, form_schema_context};
use crate::grammar::{
    DERIVED_ACTION_MEMBERSHIP_RULE, DerivationRef, E4_GENERATOR_MEMBERSHIP_GAP,
    issue_step8_registered_signatures, replay_step8_registered_signatures,
};
use pen_core::expr::Expr;
use pen_core::telescope::Telescope;
use pen_type::cubical::typed_boundary::{
    HistoricalTypedBundleEvidenceKind, RegisteredBoundaryKind,
    issue_historical_prefix_v3_c6_typed_bundle_token,
    replay_historical_prefix_v3_c6_typed_bundle_token,
};
use pen_type::elaborate::SealedSignature;
use serde::{Deserialize, Serialize};
use thiserror::Error;

pub const STEP8_R2_TOKEN_VERSION: &str = "schema2-step8-r2-typed-signatures-v1";
pub const STEP8_R2_FALSIFIER: &str = "F-Q4";

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Step8R2TypedSignaturesToken {
    pub token_version: String,
    pub rule: String,
    pub source_step: u32,
    pub predecessor_signature_digest: String,
    pub source_telescope_hash: String,
    pub source_clause_shapes: Vec<String>,
    pub registered_interpretation_overlay_replayed: bool,
    pub raw_pen_core_to_schema2_term_elaboration_proved: bool,
    pub registered_boundary_kind: String,
    pub registered_boundary_dimension: u32,
    pub registered_boundary_key_count: u64,
    pub registered_boundary_bundle_derivation_hash: String,
    pub registered_boundary_child_derivation_hash: String,
    pub registered_boundary_typing_derivation_hash: String,
    pub registered_boundary_archive_join_replayed: bool,
    pub operation_signature: String,
    pub left_unit_signature: String,
    pub cell_action_signature: String,
    pub cell_action_body: String,
    pub first_slot_orientation: bool,
    pub operation_signature_typed: bool,
    pub left_unit_signature_typed: bool,
    pub cell_action_term_typed: bool,
    pub cell_action_boundary_derived_by_map_cube: bool,
    pub schema_signature_derivation_hash: String,
    pub fq1_triggered: bool,
    pub coherence_generator_membership_decided: bool,
    pub cell_action_generator_membership_decided: bool,
    pub independent_family_tokens_issued: u32,
    pub membership_obstruction: String,
    pub falsifier: String,
    pub archived_count_used_as_input: bool,
    pub acceptance_bar_used_as_input: bool,
    pub derivation_hash: String,
}

#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum Step8R2Error {
    #[error("registered S3 boundary bundle failed: {0}")]
    Boundary(String),
    #[error("registered Step-8 signature failed: {0}")]
    Signature(String),
    #[error("registered S3 bundle metadata drifted")]
    BundleMetadataDrift,
    #[error("Step-8 telescope no longer has the registered five-clause source shape")]
    SourceShapeDrift,
    #[error("Step-8 R2 token replay mismatch")]
    ReplayMismatch,
}

fn tagged_hash(domain: &str, payload: &impl Serialize) -> String {
    let bytes = serde_json::to_vec(&(STEP8_R2_TOKEN_VERSION, domain, payload))
        .expect("Step-8 R2 proof data serializes");
    format!("blake3:{}", blake3::hash(&bytes).to_hex())
}

pub fn issue_step8_r2_typed_signatures_token() -> Result<Step8R2TypedSignaturesToken, Step8R2Error>
{
    let predecessor = SealedSignature::from_telescopes(
        (1_u32..=7)
            .map(|step| (step, Telescope::reference(step)))
            .collect(),
    );
    let current = Telescope::reference(8);
    let expected_clauses = [
        Expr::App(Box::new(Expr::Univ), Box::new(Expr::Var(1))),
        Expr::Var(1),
        Expr::PathCon(3),
        Expr::Lam(Box::new(Expr::Var(1))),
        Expr::Lam(Box::new(Expr::Var(2))),
    ];
    if current.clauses.len() != expected_clauses.len()
        || current
            .clauses
            .iter()
            .zip(expected_clauses.iter())
            .any(|(clause, expected)| clause.expr != *expected)
    {
        return Err(Step8R2Error::SourceShapeDrift);
    }
    let bundle = issue_historical_prefix_v3_c6_typed_bundle_token(
        &predecessor,
        RegisteredBoundaryKind::S3,
        &current,
    )
    .map_err(|error| Step8R2Error::Boundary(error.to_string()))?;
    replay_historical_prefix_v3_c6_typed_bundle_token(&predecessor, &current, &bundle)
        .map_err(|error| Step8R2Error::Boundary(error.to_string()))?;
    if bundle.kind() != RegisteredBoundaryKind::S3
        || bundle.step() != 8
        || bundle.dimension() != 3
        || bundle.evidence_kind() != HistoricalTypedBundleEvidenceKind::ArchivalConstantBridge
        || bundle.expected_basis_count() != bundle.realized_basis_count()
        || bundle.key_correspondence().len() as u64 != bundle.expected_basis_count()
    {
        return Err(Step8R2Error::BundleMetadataDrift);
    }

    let carrier = TypeExpr::parameter(0);
    let base = TermExpr::variable(1);
    let context = form_schema_context(vec![
        Declaration::TypeParameter {
            binder: BinderId(0),
            name: "S3".to_owned(),
            universe: 0,
        },
        Declaration::OpaqueElement {
            binder: BinderId(1),
            name: "base".to_owned(),
            ty: carrier.clone(),
        },
    ])
    .map_err(|error| Step8R2Error::Signature(error.to_string()))?;
    let bundle_ref = DerivationRef::parse(bundle.derivation_hash().to_owned())
        .map_err(|error| Step8R2Error::Signature(error.to_string()))?;
    let signatures = issue_step8_registered_signatures(context, carrier, base, bundle_ref)
        .map_err(|error| Step8R2Error::Signature(error.to_string()))?;
    replay_step8_registered_signatures(&signatures)
        .map_err(|error| Step8R2Error::Signature(error.to_string()))?;
    if !signatures.operation_signature_typed()
        || !signatures.left_unit_signature_typed()
        || !signatures.cell_action_term_typed()
        || !signatures.cell_action_boundary_derived_by_map_cube()
        || signatures.coherence_generator_membership_decided()
        || signatures.cell_action_generator_membership_decided()
    {
        return Err(Step8R2Error::Signature(
            "typed-signature or pending-membership invariant drifted".to_owned(),
        ));
    }

    let mut token = Step8R2TypedSignaturesToken {
        token_version: STEP8_R2_TOKEN_VERSION.to_owned(),
        rule: DERIVED_ACTION_MEMBERSHIP_RULE.to_owned(),
        source_step: 8,
        predecessor_signature_digest: predecessor.digest().to_owned(),
        source_telescope_hash: pen_type::elaborate::candidate_hash(&current),
        source_clause_shapes: vec![
            "App(Univ,Var(1))".to_owned(),
            "Var(1)".to_owned(),
            "PathCon(3)".to_owned(),
            "Lam(Var(1))".to_owned(),
            "Lam(Var(2))".to_owned(),
        ],
        registered_interpretation_overlay_replayed: true,
        raw_pen_core_to_schema2_term_elaboration_proved: false,
        registered_boundary_kind: "s3".to_owned(),
        registered_boundary_dimension: 3,
        registered_boundary_key_count: bundle.realized_basis_count(),
        registered_boundary_bundle_derivation_hash: bundle.derivation_hash().to_owned(),
        registered_boundary_child_derivation_hash: bundle.child_derivation_hash().to_owned(),
        registered_boundary_typing_derivation_hash: bundle
            .typed_boundary_derivation_hash()
            .to_owned(),
        registered_boundary_archive_join_replayed: true,
        operation_signature: "mu : (El(S3) * El(S3)) -> El(S3)".to_owned(),
        left_unit_signature: "Pi x:El(S3). Path El(S3) (mu(base,x)) x".to_owned(),
        cell_action_signature: "Pi x:El(S3). Cube^3(El(S3); boundary=mu(base,x))".to_owned(),
        cell_action_body: "lambda x i0 i1 i2. mu(p(i0,i1,i2),x)".to_owned(),
        first_slot_orientation: signatures.first_slot_orientation(),
        operation_signature_typed: true,
        left_unit_signature_typed: true,
        cell_action_term_typed: true,
        cell_action_boundary_derived_by_map_cube: true,
        schema_signature_derivation_hash: signatures.derivation_hash().to_owned(),
        fq1_triggered: false,
        coherence_generator_membership_decided: false,
        cell_action_generator_membership_decided: false,
        independent_family_tokens_issued: 0,
        membership_obstruction: E4_GENERATOR_MEMBERSHIP_GAP.to_owned(),
        falsifier: STEP8_R2_FALSIFIER.to_owned(),
        archived_count_used_as_input: false,
        acceptance_bar_used_as_input: false,
        derivation_hash: String::new(),
    };
    token.derivation_hash = tagged_hash("typed-signatures", &token);
    Ok(token)
}

pub fn replay_step8_r2_typed_signatures_token(
    token: &Step8R2TypedSignaturesToken,
) -> Result<(), Step8R2Error> {
    let replay = issue_step8_r2_typed_signatures_token()?;
    if replay == *token {
        Ok(())
    } else {
        Err(Step8R2Error::ReplayMismatch)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_step8_signatures_and_s3_bundle_join_replay() {
        let token = issue_step8_r2_typed_signatures_token().expect("Step-8 signatures type");
        replay_step8_r2_typed_signatures_token(&token).expect("token replays");
        assert!(token.registered_boundary_archive_join_replayed);
        assert!(token.registered_interpretation_overlay_replayed);
        assert!(!token.raw_pen_core_to_schema2_term_elaboration_proved);
        assert!(token.operation_signature_typed);
        assert!(token.left_unit_signature_typed);
        assert!(token.cell_action_term_typed);
        assert!(token.cell_action_boundary_derived_by_map_cube);
        assert!(!token.fq1_triggered);
        assert!(!token.coherence_generator_membership_decided);
        assert!(!token.cell_action_generator_membership_decided);
        assert_eq!(token.independent_family_tokens_issued, 0);
        assert!(!token.archived_count_used_as_input);
        assert!(!token.acceptance_bar_used_as_input);
    }

    #[test]
    fn orientation_membership_and_credit_mutations_fail_replay() {
        let token = issue_step8_r2_typed_signatures_token().expect("Step-8 signatures type");
        let mut orientation = token.clone();
        orientation.first_slot_orientation = false;
        assert_eq!(
            replay_step8_r2_typed_signatures_token(&orientation),
            Err(Step8R2Error::ReplayMismatch)
        );
        let mut invented_credit = token;
        invented_credit.independent_family_tokens_issued = 1;
        invented_credit.cell_action_generator_membership_decided = true;
        assert_eq!(
            replay_step8_r2_typed_signatures_token(&invented_credit),
            Err(Step8R2Error::ReplayMismatch)
        );
    }
}
